import { Member } from "./types";

export const mockMembers: Member[] = [
  {
    userId: "user-1",
    firstName: "Marc",
    lastName: "Weber",
    groupId: "group-1",
    role: "chef_de_groupe",
    email: "marc.weber@urue-algrange.fr",
    phone: "06 12 34 56 78",
    memberSince: "2019-03-01",
  },
  {
    userId: "user-2",
    firstName: "Sophie",
    lastName: "Kremer",
    groupId: "group-1",
    role: "benevole",
    email: "sophie.kremer@urue-algrange.fr",
    phone: "06 23 45 67 89",
    memberSince: "2021-09-15",
  },
  {
    userId: "user-3",
    firstName: "Julien",
    lastName: "Meyer",
    groupId: "group-1",
    role: "benevole",
    email: "julien.meyer@urue-algrange.fr",
    phone: "06 34 56 78 90",
    memberSince: "2022-05-20",
  },
  {
    userId: "user-4",
    firstName: "Camille",
    lastName: "Muller",
    groupId: "group-1",
    role: "membre",
    email: "camille.muller@urue-algrange.fr",
    phone: "06 45 67 89 01",
    memberSince: "2023-01-10",
  },
  {
    userId: "user-5",
    firstName: "Thomas",
    lastName: "Klein",
    groupId: "group-1",
    role: "membre",
    email: "thomas.klein@urue-algrange.fr",
    phone: "06 56 78 90 12",
    memberSince: "2023-11-02",
  },
  {
    userId: "user-6",
    firstName: "Nathalie",
    lastName: "Roth",
    groupId: "group-2",
    role: "chef_de_groupe",
    email: "nathalie.roth@urue-algrange.fr",
    phone: "06 67 89 01 23",
    memberSince: "2020-06-18",
  },
  {
    userId: "user-7",
    firstName: "David",
    lastName: "Wolff",
    groupId: "group-2",
    role: "benevole",
    email: "david.wolff@urue-algrange.fr",
    phone: "06 78 90 12 34",
    memberSince: "2022-08-30",
  },
  {
    userId: "user-8",
    firstName: "Claire",
    lastName: "Hoffmann",
    groupId: "group-2",
    role: "bureau",
    email: "claire.hoffmann@urue-algrange.fr",
    phone: "06 89 01 23 45",
    memberSince: "2018-04-12",
  },
];
