###############################################################################
# General
###############################################################################
quarkus.quinoa.package-manager-install.node-version=22.20.0
quarkus.quinoa.package-manager-install=true
quarkus.quinoa.ui-root-path=quinoa
###############################################################################
# Front
###############################################################################

###############################################################################
# Back
###############################################################################
%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.datasource.jdbc.url=jdbc:h2:mem:test
%dev.quarkus.datasource.username=h2
%dev.quarkus.datasource.password=admin

%dev.quarkus.hibernate-orm.schema-management.strategy=drop-and-create



