quarkus.quinoa.enable=false
quarkus.test.continuous-testing=disabled
quarkus.log.level=WARN

# Disable all Dev Services (no Docker locally)
quarkus.devservices.enabled=false

# Enable Policy Enforcement
#dev.quarkus.keycloak.policy-enforcer.enabled=

quarkus.datasource.dev-ui.allow-sql=true

# H2 file DB (path is relative to project root, file created automatically)
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:file:./data/urueDB;AUTO_SERVER=TRUE