quarkus.test.continuous-testing=enabled
quarkus.log.level=DEBUG

# Enable Policy Enforcement
#dev.quarkus.keycloak.policy-enforcer.enabled=

quarkus.datasource.dev-ui.allow-sql=true
quarkus.datasource.jdbc.url=jdbc:h2:file:./data/test/urueDB;AUTO_SERVER=TRUE