quarkus.quinoa.enable=false
quarkus.test.continuous-testing=disabled
quarkus.log.level=WARN

# Enable Policy Enforcement
#dev.quarkus.keycloak.policy-enforcer.enabled=

quarkus.datasource.dev-ui.allow-sql=true