quarkus.quinoa.enable=false
quarkus.test.continuous-testing=disabled
quarkus.log.level=WARN

quarkus.datasource.jdbc.url=jdbc:h2:file:C:/Users/peyno/IdeaProjects/LocalDBs/urue-algrange/localH2;NON_KEYWORDS=value;AUTO_SERVER=true
#quarkus.datasource.jdbc.url=jdbc:h2:file:C:/Users/mpeydam/IdeaProjects/LocalDBs/urue-algrange/localH2;NON_KEYWORDS=value;AUTO_SERVER=true
quarkus.hibernate-orm.schema-management.strategy=update

# OIDC Configuration
quarkus.oidc.enabled = false
quarkus.oidc.auth-server-url=https://app.dpeynot.fr/harpocrate/UneRoseUnEspoir-dev
quarkus.oidc.client-id=urue-algrange-api
quarkus.oidc.credentials.secret=
quarkus.oidc.application-type=web-app

# Enable Policy Enforcement
#dev.quarkus.keycloak.policy-enforcer.enabled=

quarkus.datasource.dev-ui.allow-sql=true