quarkus.test.continuous-testing=enabled
quarkus.log.level=DEBUG

# Enable Policy Enforcement
#dev.quarkus.keycloak.policy-enforcer.enabled=

quarkus.datasource.dev-ui.allow-sql=true

# In-memory database for @QuarkusTest
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
